version: 2
updates:
- package-ecosystem: pip
  directory: "/publish/"
  schedule:
    interval: monthly
    time: '11:00'
- package-ecosystem: pip
  directory: "/test/"
  schedule:
    interval: daily
    time: '11:00'
  open-pull-requests-limit: 3
  assignees:
  - ktibow
